# Introduction to Tensorflow 2.0

Tensorflow is one of the most widely usely deep learning frameworks in use today. Most data science engineers and developers rely on Tensorflow because it is not only the oldest deep learning framework but also because it's version 2.0 comes with static and dynamic computing capabilities.

In this tutorial you will learn the basics of working in Tensorflow, namely:
* creating and manipulating tensors and variables
* difference between tensors and variables

So keep reading to know how you can easily get started with tensorflow rightaway!

## Working with Tensors

*A tensor is a central unit of data in TensorFlow. It consists of primitive values stored in the shape of a multidimensional array.*

Let's start by importing Tensorflow and numpy. You can also set `tf.debugging.set_log_device_placement()` to True if you want to know which processor is used for Tensorflow computations. The function has been set to True below.

In [2]:
# Import relevant libraries
import tensorflow as tf
import numpy as np

# To track device usage
tf.debugging.set_log_device_placement(True)

Also remember that TF2.0, by default, runs eager execution. You can always check the status of execution by using `tf.executing_eagerly()`. It returns true in this case, whihc tells us that TF2.0 is executing eagerly.

In [3]:
# Check for eager execution
tf.executing_eagerly()

True

Let' s define our first tensor, just a single constant value of 11.

In [4]:
# Define a 1-element tensor
a = tf.constant(11)

a

<tf.Tensor: shape=(), dtype=int32, numpy=11>

When we call this tensor, the output received displays the shape, datatype and value of tensor. The shape here is empty because we have only defined one element. The datatype has been set to int32 by default and the value can be seen to be 11.

You can obtain the same information by printing this tensor using the `print()` command.

In [5]:
print(a)

tf.Tensor(11, shape=(), dtype=int32)


To check the shape of any tensor, you can use `.shape` attribute. As already seen above, the shape returned in this case is an empty ara=ray because the tensor has only 1 element.

In [6]:
# check shape of tensor
a.shape

TensorShape([])

For determining the data type of a tensor, you can use `.dtype` attribute.

In [7]:
# Check datatype of tensor
a.dtype

tf.int32

Now that we have worked our way around tensor `a`, let's try to perform some mathematical operations on it as well.

In [9]:
# Adding a constant to a
res1 = a + 10

res1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=21>

`res1` stores the tensor obtained from adding 10 to a. The value of this tensor, as expected, is 21. Note that you can also see on which device the computation was performed.

Its important to note here that tensors are **immutable**, which means that the content of a tensor cannot be chnaged after a tensor has been defined. any result obtained from mathematical operations will always be stored in a new tensor.

Let's define another tensor b with a few more elements.

In [10]:
# define an array of values as new tensor b
b = tf.constant([10, 20, 30, 40])

b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40])>

`b` here has 4 elements and thus the shape displayed by tensorflow is (4, ). This means the tensor is an array of 4 elements. The datatype is again int32 by default.

We can perform mathematical operations on `b` the same way as we did in `a`.

In [11]:
# add constant to b
res2 = b + 5

res2

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([15, 25, 35, 45])>

`res2` stores the tensor obtained from adding 5 to `b`. There are many ways to perform the same operation in TF2.0. 

Instead of adding 5 directly, you can also create a tensor containing constant 5 and then add it to b, as shown below.

In [12]:
# add a 1-element tensor to b
res2 = b + tf.constant(5)

res2

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([15, 25, 35, 45])>

If you want to do this operation without using the + sign, you can use `tf.add()` as well. All the three discussed methods will give you the same result.

In [13]:
# addition using tf.add()
res2 = tf.add(b, tf.constant(5))

res2

Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([15, 25, 35, 45])>

Let's define another tensor c with more than 1 dimension.

In [14]:
# 2x4 matrix
c = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8]])

c

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

`c` has 2 rows and 4 columns and the datatype is int32 by default.

What if you want to change the datatype according to your use? You can do this by using the `tf.cast()` function as shown below.

In [15]:
# change datatype to float
c = tf.cast(c, tf.float32)

c

Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

Now tensor `c` has a datatype of float32, as defined by us.

Let's try out a few more mathematical operations in Tensorflow.

In [17]:
# multiply two tensors
res3 = tf.multiply(a, b)

res3

Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([110, 220, 330, 440])>

Here, we have multiplied `a` and `b` to find a new tensor `res3`. Note that to multiply two tensors. it's essential that the datatype of both tensors is same. Hence, we cant multiply `a` and `b` with `c`.

## Tensor to Numpy arrays

Tensors can be converted into numpy arrays and vice versa in tensorflow. To do this you just need to use the `.numpy()` function with any tensor.

In [20]:
# convert tensor to array
arr_b = b.numpy()

arr_b

array([10, 20, 30, 40])

Here, we created an array `arr_b` from exiting tensor b. The reverse operation can also be done, i.e, creating a numpy array and then converting it to a tensor.

In [21]:
# define new array
arr_d = np.array([[10, 20], [30, 40], [50, 60]])

arr_d

array([[10, 20],
       [30, 40],
       [50, 60]])

You can see we have defined an array `arr_d`. Let's convert it to a tensor `d`. This is done using `tf.convert_to_tensor()` function.

In [22]:
# convert array to tensor
d = tf.convert_to_tensor(arr_d)

d

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

Thus, we have a tensor `d` of the same dimensions anc datatype as array `arr_d`. 

As TF2.0 and Numpy are so closely integrated, numpy functions can also be directly used on tensors. For example, numpy functions like `sqaure()` or `sqrt()` can be called on tensors directly.

In [23]:
# numpy operations on tensors
print(np.square(c))
print(np.sqrt(c))

[[ 1.  4.  9. 16.]
 [25. 36. 49. 64.]]
[[1.        1.4142135 1.7320508 2.       ]
 [2.236068  2.4494898 2.6457512 2.828427 ]]


But, it is important to keep in mind that such operations are not advisable. Changes made to a tensor using numpy functions are not counted in the computation graphs and this can create problems when creating a complex neural network using many different tensors.

If at any point you fail to distinguish between numpy arrays and tensors, you can call the `tf.is_tensor()` function. This function returns True when the variable passed is a tensor and False when it is not.

In [24]:
# check if given variable is tensor
print(tf.is_tensor(arr_d))
print(tf.is_tensor(d))

False
True


## Matrices in Tensorflow

Tensorflow contains a lot of useful functions for creating matrices.

For example, for creating a zero matrix, you can use `tf.zeros()` and specify the number of rows and columns required in brackets.

In [71]:
# create a 4x4 zero matrix of type int
t0 = tf.zeros([4, 4], tf.int32)

t0

Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In the same way, you can also create a unity matrix by using `tf.ones()`.

In [72]:
# create a 2x3 unit matrix of type int
t1 = tf.ones([2, 3], tf.int32)

t1

Executing op Fill in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

Matrices can also be reshaped using `tf.reshape()`. Keep in mind that the number of elements in reshaped matrix must be equal to number of elements in original matrix, or you can run into an error.

In [73]:
# reshape a 4x4 matrix to 2x8, both have 16 elements
t0_reshaped = tf.reshape(t0, (2, 8))

t0_reshaped

Executing op Reshape in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])>

## Working with Variables

*A variable acts as the placeholder for a tensor.*

Variables are recommended for computations and data manipulations in Tensorflow because they can store weights and baises attached with the tensor.

They are accessed using the `tf.Variable` class. A variable is exactly like a tensor, except the fact that it is **mutable**.

Remember how the values in a tensor couldnt be changed once defined? This is not the case with variables, and this si why variables are preferred in computation graphs. We will see this in more detail later.

Let's define a variable `v1` that contains a tensor of shape [2,3]. 

In [25]:
# define a 2x4 matrix as variable
v1 = tf.Variable([[1.5, 2.5, 3.5], [4.5, 5.5, 6.5]])

v1

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2.5, 3.5],
       [4.5, 5.5, 6.5]], dtype=float32)>

You can see that the device usage for creating a variable is much more than for creating a tensor. You obtain the same information as you saw in the case of tensor, which is the shape, datatype and value of variable.

Let's define another variable `v2`.

In [26]:
# another 2x4 matrix as variable
v2 = tf.Variable([[1, 2, 3], [4, 5, 6]])

v2

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

By default, `v2` has a datatype of int32. This datatype can also be explicitly defined during declaration.

In [76]:
# explicitly define datatype of variable
v2 = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)

v2

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

Here we set the datatype to be float32 for variable `v2` during declaration itself.

The operations on 2 variables can be done the same way as we did for tensors. 

Let's try to add `v1` and `v2` using `tf.add()`.

In [77]:
# add 2 variables
tf.add(v1, v2)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 2.5,  4.5,  6.5],
       [ 8.5, 10.5, 12.5]], dtype=float32)>

Variables can also be converted to tensors by using `tf.convert_to_tensor()`.

In [78]:
# convert variable to tensor
tf.convert_to_tensor(v1)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2.5, 3.5],
       [4.5, 5.5, 6.5]], dtype=float32)>

Variables have all the same functionalities as tensors. Just as tensors can be converted to numpy arrays, the same way variables can also be converted to numpy arrays.

In [79]:
# convert variable to numpy
v1.numpy()

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


array([[1.5, 2.5, 3.5],
       [4.5, 5.5, 6.5]], dtype=float32)

One function unique to variables is the `.assign()` function. 

Remember that variables are **mutable**, so we can change the values within a variable. This is done using the `assign()` function.

In [81]:
# change elements of v1 variable
v1.assign([[10.5, 20.5, 30.5], [40.5, 50.5, 60.5]])

v1

Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[10.5, 20.5, 30.5],
       [40.5, 50.5, 60.5]], dtype=float32)>

`assign()` can be used to replace any one element as well, as shown below.

In [82]:
# change the first element of v1 variable
v1[0, 0].assign(99)

v1

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ResourceStridedSliceAssign in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[99. , 20.5, 30.5],
       [40.5, 50.5, 60.5]], dtype=float32)>

When arithmetic operations are carried out in conjunction with `assign()`, the elements change within the called variable. No new variable is created.

In [83]:
# in place addition to v1
v1.assign_add([[1, 1, 1], [1, 1, 1]])

v1

Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100. ,  21.5,  31.5],
       [ 41.5,  51.5,  61.5]], dtype=float32)>

Now when we subtract another number from v1, it will be from the new element values obtained after addition.

In [84]:
# in place subtraction from v1
v1.assign_sub([[2, 2, 2], [2, 2, 2]])

v1

Executing op AssignSubVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[98. , 19.5, 29.5],
       [39.5, 49.5, 59.5]], dtype=float32)>

A new variable can also be declared using another variable.

For example let's define a variable `var_a`.

In [28]:
# define new variable var_a
var_a = tf.Variable([15, 20])

var_a

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15, 20])>

Now, we can define another variable `var_b` using `var_a`. This will create a copy of `var_a` as `var_b`.

In [29]:
# define new variable var_b using var_a
var_b = tf.Variable(var_a)

var_b

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15, 20])>

We can perform any operation on `var_b` but it will not change the values in `var_a`.

Two variables do not share the same memory space.

In [31]:
# change values of var_b
var_b.assign([200, 300])

print(var_b) # new value of var_b

print(var_a) # var_a same as before

Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([200, 300])>
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15, 20])>


These are some of the basic operations and concepts related to Tensorflow 2.0. These tensors and variables are the building blocks to the most complex neural networks you will come across. 

Try and experiment with these concepts on your own!

## References

* Getting started with Tensorflow 2.0 - Pluralsight (by Janani Ravi)
* [TensorFlow official documentation](https://www.tensorflow.org/guide/variable)